#!/usr/bin/env python3
"""Write an inventory of the Mega Man Legends 2 disc as Markdown.

Usage:
    python3 tools/mml2/inventory.py <disc dir> <image.bin> <out.md>

`<disc dir>` is the output of `iso.py extract`; the raw image is only used for the track layout.
Every `.BIN` archive is walked with archive.py and its entries are counted by type.
"""
import collections
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import archive  # noqa: E402

TYPE_NAMES = {
    0x00: 'stream header', 0x01: 'code/model/animation data', 0x02: 'palette', 0x03: 'texture',
    0x05: 'effect or music bank', 0x08: 'music sequence', 0x09: 'music sequence (title)',
    0x0a: 'scene data', 0x0c: 'stage data', 0x0d: 'stage geometry', 0x0e: 'music bank',
    0x0f: 'music sequence', 0x10: 'music sequence (compressed)', 0x12: 'stage table',
    0x15: 'ADPCM stream chunk',
}


def describe(counts):
    return ', '.join('%d x %s' % (n, TYPE_NAMES.get(t, 'type 0x%02x' % t))
                     for t, n in sorted(counts.items()))


def role(sub, name):
    stem = name[:-4]
    if sub == 'XA':
        return ('cutscene audio, 37.8 kHz stereo XA-ADPCM, 8 interleaved channels' if '_37' in stem
                else 'voice clips, 18.9 kHz mono XA-ADPCM, up to 32 interleaved channels')
    if sub == 'COMMON':
        table = {
            'INIT': 'boot: system font/UI textures, common effect bank',
            'GAME': 'main game overlay code, HUD textures', 'TITLE': 'title screen',
            'LOGO': 'logo screens', 'SELECT': 'selection screen', 'DEMO': 'demo',
            'STAFF': 'staff roll: streamed stereo ADPCM music and credit pictures',
            'SUBMAP': 'sub-screen (map) textures', 'SUBSCN': 'sub-screen (menu)',
        }
        if stem in table:
            return table[stem]
        if stem.startswith('G_OVER'):
            return 'game over screen: textures, jingle sequence and bank'
        if stem.startswith('PL00P'):
            return 'player model/animation set (body parts variant %s)' % stem[5:]
        if stem.startswith('PL00R'):
            return 'special weapon %s: model data, palette, effect bank' % stem[5:]
        if stem.startswith('PL') and stem.endswith('T'):
            return 'player textures (set %s)' % stem[2:4]
        if stem.startswith('PL') and 'P' in stem:
            return 'player model/animation set %s' % stem[2:4]
    if sub == 'DAT':
        n, rest = stem[2:4], stem[4:]
        if rest == 'T':
            return 'stage %s: textures, palettes, music sequence and bank' % n
        if rest == '':
            return 'stage %s: geometry, stage tables, effect banks' % n
        if rest.endswith('T'):
            return 'stage %s scene %s: textures, palettes, music' % (n, rest[:-1])
        return 'stage %s scene %s: entities (models, animation, scripts), effect/music banks' % (n, rest)
    return ''


def main():
    disc, image, out = sys.argv[1], sys.argv[2], sys.argv[3]
    lines = ['# Mega Man Legends 2 (USA, SLUS-01140) disc inventory', '']
    sectors = os.path.getsize(image) // 2352
    lines += ['Generated by `tools/mml2/inventory.py`.  Image: %d raw sectors (track 1 MODE2/2352 data, '
              'track 2 CD audio: 210 s of digital silence; ZNULL.DAT is all zeros).' % sectors, '']
    totals = collections.Counter()
    type_totals = collections.Counter()
    rows = []
    for sub in ('', 'COMMON', 'DAT', 'XA'):
        d = os.path.join(disc, sub)
        for name in sorted(os.listdir(d)):
            path = os.path.join(d, name)
            if os.path.isdir(path):
                continue
            size = os.path.getsize(path)
            rel = (sub + '/' if sub else '') + name
            totals[sub or '(root)'] += size
            if name.endswith('.BIN'):
                counts = collections.Counter(e.type for e in archive.entries(open(path, 'rb').read()))
                type_totals.update(counts)
                rows.append((rel, size, role(sub, name), describe(counts)))
            elif name.endswith('.XA'):
                rows.append((rel, size, role(sub, name), 'raw 2352-byte sectors'))
            else:
                note = {'SYSTEM.CNF': 'boot configuration', 'SLUS_011.40': 'main executable (PS-X EXE)',
                        'ZNULL.DAT': 'padding'}.get(name, '')
                rows.append((rel, size, note, ''))
    lines += ['## Summary', '', '| Directory | Bytes |', '|---|---|']
    lines += ['| %s | %d |' % kv for kv in totals.items()]
    lines += ['', '## Archive entry types (all `.BIN` files)', '', '| Type | Count | Meaning |', '|---|---|---|']
    lines += ['| 0x%02x | %d | %s |' % (t, n, TYPE_NAMES.get(t, '?')) for t, n in sorted(type_totals.items())]
    lines += ['', '## Files', '', '| File | Bytes | Role | Entries |', '|---|---|---|---|']
    lines += ['| %s | %d | %s | %s |' % r for r in rows]
    lines += ['', 'Roles are derived from file naming and entry types; stage numbers are the hex digits '
              'after `ST`.  See the docstrings in `tools/mml2/*.py` for the formats.', '']
    with open(out, 'w') as f:
        f.write('\n'.join(lines))
    print('%d files listed' % len(rows))


if __name__ == '__main__':
    main()
