#!/usr/bin/env python3
"""Generate StateRoots.java: access to every static field of the game's classes, for save states.

The recompiled module keeps static fields in module-level variables, which nothing outside the
module can list or reach. Save states (web/src/host/savestate.js) copy the game's memory by
walking its objects from the outside, so they need the statics handed over: this script reads
the field list of the patched jar with `javap` and writes a default-package class with

  capture()  an Object[] of all static values (primitives boxed), the starting points of the walk
  apply()    assign a captured array back to the non-final fields

The patched jar has every field public (tools/patch_jar.py), so plain Java can do both.

Usage: state_roots.py <patched jar> <output .java>
"""
import re
import subprocess
import sys
import zipfile

BOX = {
    'boolean': ('Boolean', 'booleanValue'), 'byte': ('Byte', 'byteValue'), 'short': ('Short', 'shortValue'),
    'char': ('Character', 'charValue'), 'int': ('Integer', 'intValue'), 'long': ('Long', 'longValue'),
    'float': ('Float', 'floatValue'), 'double': ('Double', 'doubleValue'),
}
KEYWORDS = set('''abstract assert boolean break byte case catch char class const continue default do
double else enum extends final finally float for goto if implements import instanceof int interface
long native new package private protected public return short static strictfp super switch
synchronized this throw throws transient try void volatile while true false null'''.split())


def main():
    jar, out = sys.argv[1:3]
    with zipfile.ZipFile(jar) as z:
        classes = sorted(n[:-6].replace('/', '.') for n in z.namelist() if n.endswith('.class'))
    # default-package classes only: the game's own (the jar holds nothing else)
    classes = [c for c in classes if '.' not in c and '$' not in c]
    text = subprocess.run(['javap', '-p', '-cp', jar, *classes], check=True, capture_output=True, text=True).stdout
    fields = []  # (class, type, name, final)
    current = None
    skipped = []
    for line in text.splitlines():
        m = re.match(r'^(?:public |final |abstract |synchronized )*(?:class|interface) (\S+)', line)
        if m:
            current = m.group(1)
            continue
        m = re.match(r'^\s+((?:\w+ )*)static ((?:\w+ )*)([\w.$\[\]]+) (\w+);$', line)
        if not m or current is None:
            continue
        mods = (m.group(1) + m.group(2)).split()
        ftype, name = m.group(3), m.group(4)
        final = 'final' in mods
        if final and (ftype in BOX or ftype == 'java.lang.String'):
            continue  # a constant
        if name in KEYWORDS or current in KEYWORDS:
            skipped.append(f'{current}.{name}')
            continue
        fields.append((current, ftype, name, final))
    lines = [
        '// Generated by tools/state_roots.py from the patched game jar. Do not edit.',
        '',
        '/** Save states: the static fields of the game\'s classes (see web/src/host/savestate.js). */',
        'public final class StateRoots {',
        '    private StateRoots() {',
        '    }',
        '',
        '    /** Every static value, primitives boxed; the caller adds its own roots after them. */',
        '    public static Object[] capture(Object extra) {',
        f'        Object[] v = new Object[{len(fields) + 1}];',
    ]
    for i, (cls, ftype, name, _final) in enumerate(fields):
        value = f'{cls}.{name}'
        if ftype in BOX:
            value = f'{BOX[ftype][0]}.valueOf({value})'
        lines.append(f'        v[{i}] = {value};')
    lines += [
        f'        v[{len(fields)}] = extra;',
        '        return v;',
        '    }',
        '',
        '    /** Put a captured array back (final fields keep their object; its contents were restored). */',
        '    public static void apply(Object[] v) {',
    ]
    for i, (cls, ftype, name, final) in enumerate(fields):
        if final:
            continue
        if ftype in BOX:
            lines.append(f'        {cls}.{name} = (({BOX[ftype][0]}) v[{i}]).{BOX[ftype][1]}();')
        else:
            lines.append(f'        {cls}.{name} = ({ftype}) v[{i}];')
    lines += ['    }', '}', '']
    with open(out, 'w') as f:
        f.write('\n'.join(lines))
    note = f', skipped {", ".join(skipped)} (not a Java name)' if skipped else ''
    print(f'state_roots: {len(fields)} static fields of {len(classes)} classes{note} -> {out}')


if __name__ == '__main__':
    main()
